#!/bin/bash

set -eu

cd $(dirname $0)

if [ ! -d .venv ]; then
  python3 -m venv .venv
  source .venv/bin/activate
  pip install requests bs4 pyside6
else
  source .venv/bin/activate
fi

python snumenu.py
